---
title: "project2_test"
author: "Group_01"
date: "2021/7/7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, warning = FALSE, message = FALSE, comment = NA)
```

```{r libraries}
library(tidyverse)
library(moderndive)
library(skimr)
library(kableExtra)
library(gridExtra)
library(broom)
library(plotly)
library(GGally)
```

```{r data, echo = FALSE, eval = TRUE, warning = FALSE, message = FALSE}
data <- read.csv("dataset1.csv")
```

```{r data.score}
data.score <- data %>%
  dplyr::select(Total.Number.of.Family.members,Total.Household.Income,
                Total.Food.Expenditure, Household.Head.Age, House.Floor.Area, House.Age,
                Number.of.bedrooms, Electricity)
```

```{r}
data.score %>%
  cor()
```

```{r summaries}
my_skim <- skim_with(numeric = sfl(hist = NULL))
my_skim(data.score)  %>%
  dplyr::select(-skim_type) %>%
  as_tibble() %>%
  kable(col.names = c("Variable", "Missing", "Complete", "Mean", "SD", "Min.", "1st Q.",
                      "Median", "3rd Q.", "Max."),
        caption = "Summary statistics",
        booktabs = TRUE,  digits = 2) %>%
  kable_styling(font_size = 10, latex_options = "hold_position") #create a summarized statistics table for the three variables
```

## Gender&age
```{r}
data.gender <- data %>%
  select(Household.Head.Sex, Household.Head.Age)
```

```{r}
ggplot(data = data.gender, aes(x = Household.Head.Sex, y = Household.Head.Age, fill = Household.Head.Sex)) +
  geom_boxplot() +
  labs(x = "Gender", y = "Age")+ 
  theme(legend.position = "none")
```



## balance
```{r}
data.balance <- data %>%
  select(Total.Household.Income, Total.Food.Expenditure)
```

```{r}
ggplot(data = data.balance, aes(x = Total.Household.Income, y = Total.Food.Expenditure)) +
  geom_point() +
  labs(x = "Income", y = "Expenditure") +
  geom_smooth(method = glm, se = FALSE) +
  theme(legend.position = "none")
```


## Model

```{r}
model_full <- glm(Total.Number.of.Family.members ~ Total.Household.Income +
                Total.Food.Expenditure + Household.Head.Age + House.Floor.Area + House.Age +
                Number.of.bedrooms + Electricity, data = data)
```

```{r}
model_full %>%
  summary()
```

```{r}
model_significant <- glm(Total.Number.of.Family.members ~ Total.Household.Income +
                Total.Food.Expenditure + House.Age +
                Number.of.bedrooms, data = data)
```

```{r}
model_significant %>%
  summary()
```

















